drop table if exists user
create table user (id bigint generated by default as identity (start with 1,increment by 1) NOT NULL, FIRSTNAME varchar(100) not null,LASTNAME varchar(100) not null,EMAIL varchar(100) not null,PASSWORD varchar(100) not null, primary key (id))
